### PR TITLE
add missing device types and change shutter configuration

### PR DESCRIPTION
**Pull request by MitterdorferMathias**
this is somehow a bad translation of "Fassadenbeschattung" or https://www.hella.info/de/fenster-fassade/textile-aussenbeschattungen/vorbaubeschattungen

### CODE REVIEW

**Comment by muhlba91** [comment]
i see you have a linting error. as far as i can tell `poetry run black .` might be able to automatically fix it.

if possible, can you also please squash your commits into one and apply conventional commits message formats? (here it would be e.g. „fix: add missing device types and shutter configuration“)

**Review by muhlba91 — APPROVED** [review]

**Comment by muhlba91** [comment]
thank you for spotting this! it should still work but i‘ll verify.

btw. does this fix need to go to the home assistant integration (urgently)?

**Comment by MitterdorferMathias** [comment]
I found this by helping a colleague setting up the home assistant integration.

I applied the changes locally to his setup. So currently there is no urgend need from my side.

**Comment by muhlba91** [comment]
the integration version `6.0.1` contains the newest client now.

**Pull request merged**
